# Workflow to send master to pypi
name: master to pypi
# Triggers the workflow on push to the master branch
on:
  push:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
    # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools twine build
    - name: Check extra requirements
      if: ${{ hashFiles('requirements.txt') != '' }}
      run: pip install -r requirements.txt
    - name: Build dist
      run: python -m build --no-isolation
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
